<<<<<<< HEAD
=======
version: 0.2.{build}
>>>>>>> 0.2.2
environment:
    nodejs_version: 10
    GITHUB_TOKEN:
        secure: 6ld2MBbd9Dep8sD6q3on5JHh2QBG2dSOPwS4Gp4/mG7/RLXdrB9H/ibNXI+4FeX+
branches:
  only:
    - master
    - develop
before_build:
install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    - npm -g install npm@6
    - npm -g install node-gyp
    - node --version
    - npm --version
    # install modules
    - npm install
build: off
platform:
    - x64
before_package: echo Before package
test_script:
    - npm run publish
skip_non_tags: true
artifacts:
    - path: out/make/*.exe
      name: BeetSetup